"""add onboarded_language_id to accounts

Revision ID: 19ae12c7c006
Revises: 2da5a683d651
Create Date: 2026-09-10 14:54:32.297359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ae12c7c006'
down_revision: Union[str, None] = '2da5a683d651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('onboarded_language_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'onboarded_language_id')
    # ### end Alembic commands ###
