"""add session_attachments and ticket attachment_path

Revision ID: 2da5a683d651
Revises: 8d12a31732d6
Create Date: 2026-09-09 19:53:40.591349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da5a683d651'
down_revision: Union[str, None] = '8d12a31732d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_attachments_session_id'), 'session_attachments', ['session_id'], unique=True)
    op.add_column('tickets', sa.Column('attachment_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'attachment_path')
    op.drop_index(op.f('ix_session_attachments_session_id'), table_name='session_attachments')
    op.drop_table('session_attachments')
    # ### end Alembic commands ###
