"""add sla_due_at to tickets

Revision ID: 74b6988fc3f0
Revises: 478adc4a9bc2
Create Date: 2026-09-08 14:30:44.588090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b6988fc3f0'
down_revision: Union[str, None] = '478adc4a9bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sla_due_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sla_due_at')
    # ### end Alembic commands ###
