"""add real_ticket_id to tickets

Revision ID: 8d12a31732d6
Revises: 74b6988fc3f0
Create Date: 2026-09-09 00:52:47.041009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d12a31732d6'
down_revision: Union[str, None] = '74b6988fc3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('real_ticket_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'real_ticket_id')
    # ### end Alembic commands ###
