/* ---------------------------------------------------------------------
   Dostt Support Chatbot — frontend UI strings only.
   FAQ content, refund rules, mock accounts, and fallback copy all moved to
   the Python backend (backend/app/data/, backend/app/services/) — this
   file used to hold all of that client-side before the backend existed;
   now it's just chrome text so the UI has zero business logic to drift
   out of sync with the API that's now the single source of truth.

   All 11 languages the LANGUAGES selector lists now have real translations
   here (2026-09-10 — previously only en/hi existed, so selecting any of
   the other 9 silently fell back to English chrome via I18N[lang] ||
   I18N.en, directly undercutting the product's "11 languages" pitch).
   Same pass also localized every remaining hardcoded English string in
   app.js's guided flow (call/transaction cards, empty states, ticket tab,
   attachment errors, FAQ suggestion chips) — those were previously shown
   in English regardless of the selected language even though the category
   labels next to them were already translated.

   These are a solid first pass, not yet reviewed by native speakers of
   each language — worth a native-speaker QA pass before this is
   customer-facing at scale, same as any translated copy would need.
   Ticket category/sub_category names and transaction status values are
   NOT translated here — those come from the backend as English enum-like
   strings (see backend/app/data/), and guessing translations for them
   client-side risks silently misrepresenting an enum value, so they're
   left as-is rather than invented.
--------------------------------------------------------------------- */

const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "hi", label: "हिंदी (Hindi)" },
  { code: "kn", label: "ಕನ್ನಡ (Kannada)" },
  { code: "ta", label: "தமிழ் (Tamil)" },
  { code: "te", label: "తెలుగు (Telugu)" },
  { code: "ml", label: "മലയാളം (Malayalam)" },
  { code: "mr", label: "मराठी (Marathi)" },
  { code: "bn", label: "বাংলা (Bengali)" },
  { code: "gu", label: "ગુજરાતી (Gujarati)" },
  { code: "pa", label: "ਪੰਜਾਬੀ (Punjabi)" },
  { code: "or", label: "ଓଡ଼ିଆ (Odia)" },
];

const I18N = {
  en: {
    greeting: (name) => `Hi ${name}, I'm the Dostt AI Assistant. What do you need help with today?`,
    catCalls: "Recent Calls",
    catCallsSub: "Issue with a call you made or received",
    catTx: "Recent Transactions",
    catTxSub: "Recharge, wallet or withdrawal issue",
    catOther: "Other Issues",
    catOtherSub: "Something else on your mind",
    freeTextPlaceholder: "Type your message…",
    anythingElse: "Is there anything else I can help with?",
    yes: "Yes",
    no: "No",
    closeMsg: "Thank you, you may close this chat now.",
    restart: "Restart",
    noneOfThese: "None of these — let me describe it",
    connectionError: "Sorry, I couldn't send that — please try again in a moment.",
    needsGeminiKey: "The chat agent isn't fully configured in this environment yet (no live Gemini/Vertex credentials) — everything else (session, recent activity, tickets, admin dashboard) works normally.",
    connecting: "Connecting…",
    couldntStartSession: (msg) => `Couldn't start a session: ${msg}`,
    catOtherPrompt: "Sure — go ahead and type your issue below, in your own words.",
    noRecentActivity: "No recent activity found.",
    callWith: (isVideo, name) => `${isVideo ? "Video" : "Audio"} call with ${name}`,
    durationCoins: (dur, coins) => `${dur} • ${coins} coins`,
    earningsOrPayouts: "Is this about your earnings or your payouts?",
    earningsLabel: "Earnings",
    payoutsLabel: "Payouts",
    rechargeCard: (amount, coins) => `Recharge ₹${amount} → ${coins} coins`,
    payoutCard: (amount) => `Payout ₹${amount}`,
    statusLabel: (status) => `Status: ${status}`,
    rechargeShort: (amount) => `Recharge ₹${amount}`,
    payoutShort: (amount) => `Payout ₹${amount}`,
    describeOwnWordsSubtitle: "Describe it in your own words",
    noneOfThesePrompt: "No problem — go ahead and describe what's happening, in your own words.",
    commonQuestionsLabel: "Common questions",
    couldntLoadTickets: "Couldn't load your tickets — please try again.",
    noTicketsYet: "No tickets yet. Anything you raise in chat shows up here.",
    attachmentErrorDefault: "Couldn't attach that file — try a smaller image (JPEG/PNG/WEBP/HEIC, under 8MB).",
  },
  hi: {
    greeting: (name) => `नमस्ते ${name}, मैं Dostt AI Assistant हूँ। आज आपकी क्या मदद कर सकता हूँ?`,
    catCalls: "हाल की कॉल्स",
    catCallsSub: "किसी कॉल से जुड़ी समस्या",
    catTx: "हाल के लेन-देन",
    catTxSub: "रिचार्ज, वॉलेट या निकासी से जुड़ी समस्या",
    catOther: "अन्य समस्या",
    catOtherSub: "कुछ और बताना है",
    freeTextPlaceholder: "अपना संदेश लिखें…",
    anythingElse: "क्या मैं किसी और चीज़ में मदद कर सकता हूँ?",
    yes: "हाँ",
    no: "नहीं",
    closeMsg: "धन्यवाद, अब आप यह चैट बंद कर सकते हैं।",
    restart: "फिर से शुरू करें",
    noneOfThese: "इनमें से कोई नहीं — मुझे बताने दें",
    connectionError: "क्षमा करें, भेज नहीं सका — कृपया फिर से प्रयास करें।",
    needsGeminiKey: "इस वातावरण में चैट एजेंट पूरी तरह कॉन्फ़िगर नहीं है — बाकी सब कुछ सामान्य रूप से काम करता है।",
    connecting: "कनेक्ट हो रहा है…",
    couldntStartSession: (msg) => `सेशन शुरू नहीं हो सका: ${msg}`,
    catOtherPrompt: "ठीक है — नीचे अपनी समस्या अपने शब्दों में लिखें।",
    noRecentActivity: "कोई हाल की गतिविधि नहीं मिली।",
    callWith: (isVideo, name) => `${name} के साथ ${isVideo ? "वीडियो" : "ऑडियो"} कॉल`,
    durationCoins: (dur, coins) => `${dur} • ${coins} कॉइन्स`,
    earningsOrPayouts: "क्या यह आपकी कमाई या भुगतान से जुड़ा है?",
    earningsLabel: "कमाई",
    payoutsLabel: "भुगतान",
    rechargeCard: (amount, coins) => `रिचार्ज ₹${amount} → ${coins} कॉइन्स`,
    payoutCard: (amount) => `भुगतान ₹${amount}`,
    statusLabel: (status) => `स्थिति: ${status}`,
    rechargeShort: (amount) => `रिचार्ज ₹${amount}`,
    payoutShort: (amount) => `भुगतान ₹${amount}`,
    describeOwnWordsSubtitle: "अपने शब्दों में बताएं",
    noneOfThesePrompt: "कोई बात नहीं — बताइए क्या हो रहा है, अपने शब्दों में।",
    commonQuestionsLabel: "सामान्य प्रश्न",
    couldntLoadTickets: "आपके टिकट लोड नहीं हो सके — कृपया फिर से प्रयास करें।",
    noTicketsYet: "अभी तक कोई टिकट नहीं है। चैट में जो भी आप उठाएंगे वह यहां दिखेगा।",
    attachmentErrorDefault: "फ़ाइल जोड़ी नहीं जा सकी — कृपया छोटी इमेज आज़माएं (JPEG/PNG/WEBP/HEIC, 8MB से कम)।",
  },
  kn: {
    greeting: (name) => `ನಮಸ್ಕಾರ ${name}, ನಾನು Dostt AI Assistant. ಇಂದು ನಿಮಗೆ ಯಾವ ಸಹಾಯ ಬೇಕು?`,
    catCalls: "ಇತ್ತೀಚಿನ ಕರೆಗಳು",
    catCallsSub: "ಕರೆಗೆ ಸಂಬಂಧಿಸಿದ ಸಮಸ್ಯೆ",
    catTx: "ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು",
    catTxSub: "ರೀಚಾರ್ಜ್, ವಾಲೆಟ್ ಅಥವಾ ವಿತ್‌ಡ್ರಾವಲ್ ಸಮಸ್ಯೆ",
    catOther: "ಇತರ ಸಮಸ್ಯೆಗಳು",
    catOtherSub: "ಬೇರೆ ಏನಾದರೂ ಹೇಳಬೇಕೆ",
    freeTextPlaceholder: "ನಿಮ್ಮ ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ…",
    anythingElse: "ಇನ್ನೇನಾದರೂ ಸಹಾಯ ಬೇಕೆ?",
    yes: "ಹೌದು",
    no: "ಇಲ್ಲ",
    closeMsg: "ಧನ್ಯವಾದಗಳು, ಈಗ ನೀವು ಈ ಚಾಟ್ ಅನ್ನು ಮುಚ್ಚಬಹುದು.",
    restart: "ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ",
    noneOfThese: "ಇವುಗಳಲ್ಲಿ ಯಾವುದೂ ಅಲ್ಲ — ನನಗೆ ವಿವರಿಸಲು ಬಿಡಿ",
    connectionError: "ಕ್ಷಮಿಸಿ, ಕಳುಹಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ — ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    needsGeminiKey: "ಈ ಪರಿಸರದಲ್ಲಿ ಚಾಟ್ ಏಜೆಂಟ್ ಇನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಕಾನ್ಫಿಗರ್ ಆಗಿಲ್ಲ — ಉಳಿದೆಲ್ಲಾ ಸಾಮಾನ್ಯವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ.",
    connecting: "ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ…",
    couldntStartSession: (msg) => `ಸೆಷನ್ ಪ್ರಾರಂಭಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ: ${msg}`,
    catOtherPrompt: "ಸರಿ — ಕೆಳಗೆ ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ನಿಮ್ಮ ಸ್ವಂತ ಮಾತುಗಳಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ.",
    noRecentActivity: "ಯಾವುದೇ ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ ಕಂಡುಬಂದಿಲ್ಲ.",
    callWith: (isVideo, name) => `${name} ಜೊತೆ ${isVideo ? "ವೀಡಿಯೋ" : "ಆಡಿಯೋ"} ಕರೆ`,
    durationCoins: (dur, coins) => `${dur} • ${coins} ಕಾಯಿನ್ಸ್`,
    earningsOrPayouts: "ಇದು ನಿಮ್ಮ ಗಳಿಕೆ ಅಥವಾ ಪಾವತಿಗೆ ಸಂಬಂಧಿಸಿದೆಯೇ?",
    earningsLabel: "ಗಳಿಕೆ",
    payoutsLabel: "ಪಾವತಿಗಳು",
    rechargeCard: (amount, coins) => `ರೀಚಾರ್ಜ್ ₹${amount} → ${coins} ಕಾಯಿನ್ಸ್`,
    payoutCard: (amount) => `ಪಾವತಿ ₹${amount}`,
    statusLabel: (status) => `ಸ್ಥಿತಿ: ${status}`,
    rechargeShort: (amount) => `ರೀಚಾರ್ಜ್ ₹${amount}`,
    payoutShort: (amount) => `ಪಾವತಿ ₹${amount}`,
    describeOwnWordsSubtitle: "ನಿಮ್ಮ ಸ್ವಂತ ಮಾತುಗಳಲ್ಲಿ ವಿವರಿಸಿ",
    noneOfThesePrompt: "ಪರವಾಗಿಲ್ಲ — ಏನಾಗುತ್ತಿದೆ ಎಂದು ನಿಮ್ಮ ಸ್ವಂತ ಮಾತುಗಳಲ್ಲಿ ವಿವರಿಸಿ.",
    commonQuestionsLabel: "ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು",
    couldntLoadTickets: "ನಿಮ್ಮ ಟಿಕೆಟ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ — ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    noTicketsYet: "ಇನ್ನೂ ಯಾವುದೇ ಟಿಕೆಟ್ ಇಲ್ಲ. ಚಾಟ್‌ನಲ್ಲಿ ನೀವು ಎತ್ತುವ ಯಾವುದೇ ವಿಷಯ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
    attachmentErrorDefault: "ಆ ಫೈಲ್ ಲಗತ್ತಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ — ಚಿಕ್ಕ ಚಿತ್ರವನ್ನು ಪ್ರಯತ್ನಿಸಿ (JPEG/PNG/WEBP/HEIC, 8MB ಗಿಂತ ಕಡಿಮೆ).",
  },
  ta: {
    greeting: (name) => `வணக்கம் ${name}, நான் Dostt AI Assistant. இன்று உங்களுக்கு என்ன உதவி வேண்டும்?`,
    catCalls: "சமீபத்திய அழைப்புகள்",
    catCallsSub: "அழைப்பு தொடர்பான சிக்கல்",
    catTx: "சமீபத்திய பரிவர்த்தனைகள்",
    catTxSub: "ரீசார்ஜ், வாலட் அல்லது திரும்பப்பெறுதல் சிக்கல்",
    catOther: "மற்ற சிக்கல்கள்",
    catOtherSub: "வேறு ஏதாவது சொல்ல வேண்டுமா",
    freeTextPlaceholder: "உங்கள் செய்தியை தட்டச்சு செய்யவும்…",
    anythingElse: "வேறு ஏதேனும் உதவி தேவையா?",
    yes: "ஆம்",
    no: "இல்லை",
    closeMsg: "நன்றி, இப்போது இந்த அரட்டையை மூடலாம்.",
    restart: "மீண்டும் தொடங்கு",
    noneOfThese: "இவை எதுவும் இல்லை — நான் விளக்குகிறேன்",
    connectionError: "மன்னிக்கவும், அனுப்ப முடியவில்லை — தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
    needsGeminiKey: "இந்த சூழலில் அரட்டை ஏஜெண்ட் இன்னும் முழுமையாக கட்டமைக்கப்படவில்லை — மற்ற அனைத்தும் இயல்பாக செயல்படும்.",
    connecting: "இணைக்கிறது…",
    couldntStartSession: (msg) => `அமர்வைத் தொடங்க முடியவில்லை: ${msg}`,
    catOtherPrompt: "சரி — கீழே உங்கள் பிரச்சினையை உங்கள் சொந்த வார்த்தைகளில் தட்டச்சு செய்யவும்.",
    noRecentActivity: "சமீபத்திய செயல்பாடு எதுவும் இல்லை.",
    callWith: (isVideo, name) => `${name} உடன் ${isVideo ? "வீடியோ" : "ஆடியோ"} அழைப்பு`,
    durationCoins: (dur, coins) => `${dur} • ${coins} நாணயங்கள்`,
    earningsOrPayouts: "இது உங்கள் வருமானம் அல்லது கொடுப்பனவு தொடர்பானதா?",
    earningsLabel: "வருமானம்",
    payoutsLabel: "கொடுப்பனவுகள்",
    rechargeCard: (amount, coins) => `ரீசார்ஜ் ₹${amount} → ${coins} நாணயங்கள்`,
    payoutCard: (amount) => `கொடுப்பனவு ₹${amount}`,
    statusLabel: (status) => `நிலை: ${status}`,
    rechargeShort: (amount) => `ரீசார்ஜ் ₹${amount}`,
    payoutShort: (amount) => `கொடுப்பனவு ₹${amount}`,
    describeOwnWordsSubtitle: "உங்கள் சொந்த வார்த்தைகளில் விவரிக்கவும்",
    noneOfThesePrompt: "பரவாயில்லை — என்ன நடக்கிறது என்பதை உங்கள் சொந்த வார்த்தைகளில் விவரிக்கவும்.",
    commonQuestionsLabel: "பொதுவான கேள்விகள்",
    couldntLoadTickets: "உங்கள் டிக்கெட்டுகளை ஏற்ற முடியவில்லை — மீண்டும் முயற்சிக்கவும்.",
    noTicketsYet: "இதுவரை டிக்கெட் இல்லை. நீங்கள் அரட்டையில் எழுப்பும் எதுவும் இங்கே தோன்றும்.",
    attachmentErrorDefault: "அந்த கோப்பை இணைக்க முடியவில்லை — சிறிய படத்தை முயற்சிக்கவும் (JPEG/PNG/WEBP/HEIC, 8MB க்கும் குறைவாக).",
  },
  te: {
    greeting: (name) => `నమస్తే ${name}, నేను Dostt AI Assistant. ఈరోజు మీకు ఏ సహాయం కావాలి?`,
    catCalls: "ఇటీవలి కాల్స్",
    catCallsSub: "కాల్‌కి సంబంధించిన సమస్య",
    catTx: "ఇటీవలి లావాదేవీలు",
    catTxSub: "రీఛార్జ్, వాలెట్ లేదా విత్‌డ్రా సమస్య",
    catOther: "ఇతర సమస్యలు",
    catOtherSub: "మరేదైనా చెప్పాలా",
    freeTextPlaceholder: "మీ సందేశాన్ని టైప్ చేయండి…",
    anythingElse: "మరేదైనా సహాయం కావాలా?",
    yes: "అవును",
    no: "లేదు",
    closeMsg: "ధన్యవాదాలు, ఇప్పుడు మీరు ఈ చాట్‌ను మూసివేయవచ్చు.",
    restart: "మళ్లీ ప్రారంభించండి",
    noneOfThese: "వీటిలో ఏదీ కాదు — నన్ను వివరించనివ్వండి",
    connectionError: "క్షమించండి, పంపలేకపోయాము — దయచేసి మళ్లీ ప్రయత్నించండి.",
    needsGeminiKey: "ఈ వాతావరణంలో చాట్ ఏజెంట్ ఇంకా పూర్తిగా కాన్ఫిగర్ చేయబడలేదు — మిగతావన్నీ సాధారణంగా పనిచేస్తాయి.",
    connecting: "కనెక్ట్ అవుతోంది…",
    couldntStartSession: (msg) => `సెషన్ ప్రారంభించలేకపోయాము: ${msg}`,
    catOtherPrompt: "సరే — మీ సమస్యను మీ సొంత మాటల్లో కింద టైప్ చేయండి.",
    noRecentActivity: "ఇటీవలి కార్యకలాపం ఏదీ కనిపించలేదు.",
    callWith: (isVideo, name) => `${name} తో ${isVideo ? "వీడియో" : "ఆడియో"} కాల్`,
    durationCoins: (dur, coins) => `${dur} • ${coins} కాయిన్స్`,
    earningsOrPayouts: "ఇది మీ సంపాదన లేదా చెల్లింపుకు సంబంధించినదా?",
    earningsLabel: "సంపాదన",
    payoutsLabel: "చెల్లింపులు",
    rechargeCard: (amount, coins) => `రీఛార్జ్ ₹${amount} → ${coins} కాయిన్స్`,
    payoutCard: (amount) => `చెల్లింపు ₹${amount}`,
    statusLabel: (status) => `స్థితి: ${status}`,
    rechargeShort: (amount) => `రీఛార్జ్ ₹${amount}`,
    payoutShort: (amount) => `చెల్లింపు ₹${amount}`,
    describeOwnWordsSubtitle: "మీ సొంత మాటల్లో వివరించండి",
    noneOfThesePrompt: "పర్వాలేదు — ఏమి జరుగుతుందో మీ సొంత మాటల్లో వివరించండి.",
    commonQuestionsLabel: "సాధారణ ప్రశ్నలు",
    couldntLoadTickets: "మీ టికెట్‌లను లోడ్ చేయలేకపోయాము — దయచేసి మళ్లీ ప్రయత్నించండి.",
    noTicketsYet: "ఇంకా టికెట్లు లేవు. మీరు చాట్‌లో లేవనెత్తినవి ఇక్కడ కనిపిస్తాయి.",
    attachmentErrorDefault: "ఆ ఫైల్‌ను జోడించలేకపోయాము — చిన్న చిత్రాన్ని ప్రయత్నించండి (JPEG/PNG/WEBP/HEIC, 8MB కంటే తక్కువ).",
  },
  ml: {
    greeting: (name) => `നമസ്കാരം ${name}, ഞാൻ Dostt AI Assistant ആണ്. ഇന്ന് നിങ്ങൾക്ക് എന്ത് സഹായം വേണം?`,
    catCalls: "സമീപകാല കോളുകൾ",
    catCallsSub: "ഒരു കോളുമായി ബന്ധപ്പെട്ട പ്രശ്നം",
    catTx: "സമീപകാല ഇടപാടുകൾ",
    catTxSub: "റീചാർജ്, വാലറ്റ് അല്ലെങ്കിൽ പിൻവലിക്കൽ പ്രശ്നം",
    catOther: "മറ്റ് പ്രശ്നങ്ങൾ",
    catOtherSub: "മറ്റെന്തെങ്കിലും പറയണോ",
    freeTextPlaceholder: "നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക…",
    anythingElse: "വേറെ എന്തെങ്കിലും സഹായം വേണോ?",
    yes: "അതെ",
    no: "ഇല്ല",
    closeMsg: "നന്ദി, ഇപ്പോൾ നിങ്ങൾക്ക് ഈ ചാറ്റ് അടയ്ക്കാം.",
    restart: "വീണ്ടും ആരംഭിക്കുക",
    noneOfThese: "ഇവയൊന്നുമല്ല — എന്നെ വിശദീകരിക്കാൻ അനുവദിക്കൂ",
    connectionError: "ക്ഷമിക്കണം, അയയ്ക്കാൻ കഴിഞ്ഞില്ല — ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    needsGeminiKey: "ഈ പരിതസ്ഥിതിയിൽ ചാറ്റ് ഏജന്റ് ഇതുവരെ പൂർണ്ണമായി കോൺഫിഗർ ചെയ്തിട്ടില്ല — മറ്റെല്ലാം സാധാരണ പോലെ പ്രവർത്തിക്കുന്നു.",
    connecting: "ബന്ധിപ്പിക്കുന്നു…",
    couldntStartSession: (msg) => `സെഷൻ ആരംഭിക്കാൻ കഴിഞ്ഞില്ല: ${msg}`,
    catOtherPrompt: "ശരി — നിങ്ങളുടെ പ്രശ്നം താഴെ സ്വന്തം വാക്കുകളിൽ ടൈപ്പ് ചെയ്യുക.",
    noRecentActivity: "സമീപകാല പ്രവർത്തനങ്ങളൊന്നും കണ്ടെത്തിയില്ല.",
    callWith: (isVideo, name) => `${name} കൂടെ ${isVideo ? "വീഡിയോ" : "ഓഡിയോ"} കോൾ`,
    durationCoins: (dur, coins) => `${dur} • ${coins} കോയിനുകൾ`,
    earningsOrPayouts: "ഇത് നിങ്ങളുടെ വരുമാനത്തെക്കുറിച്ചാണോ അതോ പണമടയ്ക്കലിനെക്കുറിച്ചാണോ?",
    earningsLabel: "വരുമാനം",
    payoutsLabel: "പണമടയ്ക്കൽ",
    rechargeCard: (amount, coins) => `റീചാർജ് ₹${amount} → ${coins} കോയിനുകൾ`,
    payoutCard: (amount) => `പണമടയ്ക്കൽ ₹${amount}`,
    statusLabel: (status) => `നില: ${status}`,
    rechargeShort: (amount) => `റീചാർജ് ₹${amount}`,
    payoutShort: (amount) => `പണമടയ്ക്കൽ ₹${amount}`,
    describeOwnWordsSubtitle: "സ്വന്തം വാക്കുകളിൽ വിവരിക്കുക",
    noneOfThesePrompt: "സാരമില്ല — എന്താണ് സംഭവിക്കുന്നതെന്ന് സ്വന്തം വാക്കുകളിൽ വിവരിക്കുക.",
    commonQuestionsLabel: "സാധാരണ ചോദ്യങ്ങൾ",
    couldntLoadTickets: "നിങ്ങളുടെ ടിക്കറ്റുകൾ ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല — ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    noTicketsYet: "ഇതുവരെ ടിക്കറ്റുകൾ ഇല്ല. ചാറ്റിൽ നിങ്ങൾ ഉന്നയിക്കുന്നത് ഇവിടെ കാണിക്കും.",
    attachmentErrorDefault: "ആ ഫയൽ ചേർക്കാൻ കഴിഞ്ഞില്ല — ചെറിയ ചിത്രം ശ്രമിക്കുക (JPEG/PNG/WEBP/HEIC, 8MB-ൽ താഴെ).",
  },
  mr: {
    greeting: (name) => `नमस्कार ${name}, मी Dostt AI Assistant आहे. आज तुम्हाला कोणती मदत हवी आहे?`,
    catCalls: "अलीकडील कॉल्स",
    catCallsSub: "कॉलशी संबंधित समस्या",
    catTx: "अलीकडील व्यवहार",
    catTxSub: "रिचार्ज, वॉलेट किंवा पैसे काढण्याची समस्या",
    catOther: "इतर समस्या",
    catOtherSub: "आणखी काही सांगायचे आहे का",
    freeTextPlaceholder: "तुमचा संदेश टाइप करा…",
    anythingElse: "आणखी काही मदत हवी आहे का?",
    yes: "होय",
    no: "नाही",
    closeMsg: "धन्यवाद, आता तुम्ही हे चॅट बंद करू शकता.",
    restart: "पुन्हा सुरू करा",
    noneOfThese: "यापैकी काहीही नाही — मला सांगू द्या",
    connectionError: "क्षमस्व, पाठवता आले नाही — कृपया पुन्हा प्रयत्न करा.",
    needsGeminiKey: "या वातावरणात चॅट एजंट अद्याप पूर्णपणे कॉन्फिगर केलेला नाही — बाकी सर्व सामान्यपणे कार्य करते.",
    connecting: "कनेक्ट होत आहे…",
    couldntStartSession: (msg) => `सेशन सुरू करता आले नाही: ${msg}`,
    catOtherPrompt: "ठीक आहे — खाली तुमची समस्या तुमच्या शब्दांत टाइप करा.",
    noRecentActivity: "अलीकडील कोणतीही क्रिया आढळली नाही.",
    callWith: (isVideo, name) => `${name} सोबत ${isVideo ? "व्हिडिओ" : "ऑडिओ"} कॉल`,
    durationCoins: (dur, coins) => `${dur} • ${coins} कॉइन्स`,
    earningsOrPayouts: "हे तुमच्या कमाईबद्दल आहे की पेआउटबद्दल?",
    earningsLabel: "कमाई",
    payoutsLabel: "पेआउट्स",
    rechargeCard: (amount, coins) => `रिचार्ज ₹${amount} → ${coins} कॉइन्स`,
    payoutCard: (amount) => `पेआउट ₹${amount}`,
    statusLabel: (status) => `स्थिती: ${status}`,
    rechargeShort: (amount) => `रिचार्ज ₹${amount}`,
    payoutShort: (amount) => `पेआउट ₹${amount}`,
    describeOwnWordsSubtitle: "तुमच्या शब्दांत वर्णन करा",
    noneOfThesePrompt: "हरकत नाही — काय होत आहे ते तुमच्या शब्दांत सांगा.",
    commonQuestionsLabel: "सामान्य प्रश्न",
    couldntLoadTickets: "तुमची तिकिटे लोड करता आली नाहीत — कृपया पुन्हा प्रयत्न करा.",
    noTicketsYet: "अजून कोणतेही तिकीट नाही. चॅटमध्ये तुम्ही जे उपस्थित कराल ते इथे दिसेल.",
    attachmentErrorDefault: "ती फाईल जोडता आली नाही — कृपया लहान इमेज वापरून पहा (JPEG/PNG/WEBP/HEIC, 8MB पेक्षा कमी).",
  },
  bn: {
    greeting: (name) => `নমস্কার ${name}, আমি Dostt AI Assistant। আজ আপনার কী সাহায্য দরকার?`,
    catCalls: "সাম্প্রতিক কল",
    catCallsSub: "কল সংক্রান্ত সমস্যা",
    catTx: "সাম্প্রতিক লেনদেন",
    catTxSub: "রিচার্জ, ওয়ালেট বা উত্তোলন সংক্রান্ত সমস্যা",
    catOther: "অন্যান্য সমস্যা",
    catOtherSub: "আর কিছু বলতে চান",
    freeTextPlaceholder: "আপনার বার্তা টাইপ করুন…",
    anythingElse: "আর কিছুতে সাহায্য দরকার?",
    yes: "হ্যাঁ",
    no: "না",
    closeMsg: "ধন্যবাদ, এখন আপনি এই চ্যাট বন্ধ করতে পারেন।",
    restart: "আবার শুরু করুন",
    noneOfThese: "এগুলোর কোনোটিই নয় — আমাকে বলতে দিন",
    connectionError: "দুঃখিত, পাঠানো যায়নি — অনুগ্রহ করে আবার চেষ্টা করুন।",
    needsGeminiKey: "এই পরিবেশে চ্যাট এজেন্ট এখনও সম্পূর্ণভাবে কনফিগার করা হয়নি — বাকি সব স্বাভাবিকভাবে কাজ করে।",
    connecting: "সংযোগ করা হচ্ছে…",
    couldntStartSession: (msg) => `সেশন শুরু করা যায়নি: ${msg}`,
    catOtherPrompt: "ঠিক আছে — নিচে আপনার সমস্যা নিজের ভাষায় লিখুন।",
    noRecentActivity: "কোনো সাম্প্রতিক কার্যকলাপ পাওয়া যায়নি।",
    callWith: (isVideo, name) => `${name} এর সাথে ${isVideo ? "ভিডিও" : "অডিও"} কল`,
    durationCoins: (dur, coins) => `${dur} • ${coins} কয়েন`,
    earningsOrPayouts: "এটা কি আপনার আয় নাকি পেআউট সংক্রান্ত?",
    earningsLabel: "আয়",
    payoutsLabel: "পেআউট",
    rechargeCard: (amount, coins) => `রিচার্জ ₹${amount} → ${coins} কয়েন`,
    payoutCard: (amount) => `পেআউট ₹${amount}`,
    statusLabel: (status) => `অবস্থা: ${status}`,
    rechargeShort: (amount) => `রিচার্জ ₹${amount}`,
    payoutShort: (amount) => `পেআউট ₹${amount}`,
    describeOwnWordsSubtitle: "নিজের ভাষায় বর্ণনা করুন",
    noneOfThesePrompt: "কোনো ব্যাপার না — কী হচ্ছে তা নিজের ভাষায় বর্ণনা করুন।",
    commonQuestionsLabel: "সাধারণ প্রশ্ন",
    couldntLoadTickets: "আপনার টিকিট লোড করা যায়নি — অনুগ্রহ করে আবার চেষ্টা করুন।",
    noTicketsYet: "এখনও কোনো টিকিট নেই। চ্যাটে আপনি যা তুলবেন তা এখানে দেখা যাবে।",
    attachmentErrorDefault: "সেই ফাইলটি যুক্ত করা যায়নি — ছোট ছবি ব্যবহার করে দেখুন (JPEG/PNG/WEBP/HEIC, 8MB এর কম)।",
  },
  gu: {
    greeting: (name) => `નમસ્તે ${name}, હું Dostt AI Assistant છું. આજે તમને શું મદદ જોઈએ છે?`,
    catCalls: "તાજેતરના કૉલ્સ",
    catCallsSub: "કૉલ સંબંધિત સમસ્યા",
    catTx: "તાજેતરના વ્યવહારો",
    catTxSub: "રિચાર્જ, વોલેટ અથવા ઉપાડ સંબંધિત સમસ્યા",
    catOther: "અન્ય સમસ્યાઓ",
    catOtherSub: "બીજું કંઈ કહેવું છે",
    freeTextPlaceholder: "તમારો સંદેશ ટાઈપ કરો…",
    anythingElse: "બીજી કોઈ મદદ જોઈએ છે?",
    yes: "હા",
    no: "ના",
    closeMsg: "આભાર, હવે તમે આ ચેટ બંધ કરી શકો છો.",
    restart: "ફરીથી શરૂ કરો",
    noneOfThese: "આમાંથી કંઈ નહીં — મને જણાવવા દો",
    connectionError: "માફ કરશો, મોકલી શકાયું નથી — કૃપા કરી ફરી પ્રયાસ કરો.",
    needsGeminiKey: "આ વાતાવરણમાં ચેટ એજન્ટ હજુ સંપૂર્ણ રીતે કન્ફિગર થયેલ નથી — બાકીનું બધું સામાન્ય રીતે કામ કરે છે.",
    connecting: "કનેક્ટ થઈ રહ્યું છે…",
    couldntStartSession: (msg) => `સેશન શરૂ કરી શકાયું નહીં: ${msg}`,
    catOtherPrompt: "ઠીક છે — નીચે તમારી સમસ્યા તમારા શબ્દોમાં ટાઈપ કરો.",
    noRecentActivity: "કોઈ તાજેતરની પ્રવૃત્તિ મળી નથી.",
    callWith: (isVideo, name) => `${name} સાથે ${isVideo ? "વિડિઓ" : "ઓડિયો"} કૉલ`,
    durationCoins: (dur, coins) => `${dur} • ${coins} કોઈન્સ`,
    earningsOrPayouts: "શું આ તમારી કમાણી કે ઉપાડ સંબંધિત છે?",
    earningsLabel: "કમાણી",
    payoutsLabel: "ઉપાડ",
    rechargeCard: (amount, coins) => `રિચાર્જ ₹${amount} → ${coins} કોઈન્સ`,
    payoutCard: (amount) => `ઉપાડ ₹${amount}`,
    statusLabel: (status) => `સ્થિતિ: ${status}`,
    rechargeShort: (amount) => `રિચાર્જ ₹${amount}`,
    payoutShort: (amount) => `ઉપાડ ₹${amount}`,
    describeOwnWordsSubtitle: "તમારા શબ્દોમાં વર્ણન કરો",
    noneOfThesePrompt: "કોઈ વાંધો નહીં — શું થઈ રહ્યું છે તે તમારા શબ્દોમાં જણાવો.",
    commonQuestionsLabel: "સામાન્ય પ્રશ્નો",
    couldntLoadTickets: "તમારી ટિકિટ લોડ કરી શકાઈ નથી — કૃપા કરી ફરી પ્રયાસ કરો.",
    noTicketsYet: "હજુ સુધી કોઈ ટિકિટ નથી. ચેટમાં તમે જે ઉઠાવશો તે અહીં દેખાશે.",
    attachmentErrorDefault: "તે ફાઇલ જોડી શકાઈ નથી — નાની ઈમેજ અજમાવો (JPEG/PNG/WEBP/HEIC, 8MBથી ઓછી).",
  },
  pa: {
    greeting: (name) => `ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ${name}, ਮੈਂ Dostt AI Assistant ਹਾਂ। ਅੱਜ ਤੁਹਾਨੂੰ ਕੀ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?`,
    catCalls: "ਹਾਲੀਆ ਕਾਲਾਂ",
    catCallsSub: "ਕਾਲ ਨਾਲ ਸਬੰਧਤ ਸਮੱਸਿਆ",
    catTx: "ਹਾਲੀਆ ਲੈਣ-ਦੇਣ",
    catTxSub: "ਰੀਚਾਰਜ, ਵਾਲਿਟ ਜਾਂ ਕਢਵਾਉਣ ਦੀ ਸਮੱਸਿਆ",
    catOther: "ਹੋਰ ਸਮੱਸਿਆਵਾਂ",
    catOtherSub: "ਕੁਝ ਹੋਰ ਦੱਸਣਾ ਹੈ",
    freeTextPlaceholder: "ਆਪਣਾ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ…",
    anythingElse: "ਕੀ ਕੋਈ ਹੋਰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?",
    yes: "ਹਾਂ",
    no: "ਨਹੀਂ",
    closeMsg: "ਧੰਨਵਾਦ, ਹੁਣ ਤੁਸੀਂ ਇਹ ਚੈਟ ਬੰਦ ਕਰ ਸਕਦੇ ਹੋ।",
    restart: "ਦੁਬਾਰਾ ਸ਼ੁਰੂ ਕਰੋ",
    noneOfThese: "ਇਹਨਾਂ ਵਿੱਚੋਂ ਕੋਈ ਨਹੀਂ — ਮੈਨੂੰ ਦੱਸਣ ਦਿਓ",
    connectionError: "ਮਾਫ਼ ਕਰਨਾ, ਭੇਜ ਨਹੀਂ ਸਕੇ — ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    needsGeminiKey: "ਇਸ ਵਾਤਾਵਰਣ ਵਿੱਚ ਚੈਟ ਏਜੰਟ ਅਜੇ ਪੂਰੀ ਤਰ੍ਹਾਂ ਕੌਂਫਿਗਰ ਨਹੀਂ ਹੋਇਆ — ਬਾਕੀ ਸਭ ਆਮ ਵਾਂਗ ਕੰਮ ਕਰਦਾ ਹੈ।",
    connecting: "ਕਨੈਕਟ ਹੋ ਰਿਹਾ ਹੈ…",
    couldntStartSession: (msg) => `ਸੈਸ਼ਨ ਸ਼ੁਰੂ ਨਹੀਂ ਹੋ ਸਕਿਆ: ${msg}`,
    catOtherPrompt: "ਠੀਕ ਹੈ — ਹੇਠਾਂ ਆਪਣੀ ਸਮੱਸਿਆ ਆਪਣੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਲਿਖੋ।",
    noRecentActivity: "ਕੋਈ ਹਾਲੀਆ ਗਤੀਵਿਧੀ ਨਹੀਂ ਮਿਲੀ।",
    callWith: (isVideo, name) => `${name} ਨਾਲ ${isVideo ? "ਵੀਡੀਓ" : "ਆਡੀਓ"} ਕਾਲ`,
    durationCoins: (dur, coins) => `${dur} • ${coins} ਕੋਇਨ`,
    earningsOrPayouts: "ਕੀ ਇਹ ਤੁਹਾਡੀ ਕਮਾਈ ਜਾਂ ਭੁਗਤਾਨ ਬਾਰੇ ਹੈ?",
    earningsLabel: "ਕਮਾਈ",
    payoutsLabel: "ਭੁਗਤਾਨ",
    rechargeCard: (amount, coins) => `ਰੀਚਾਰਜ ₹${amount} → ${coins} ਕੋਇਨ`,
    payoutCard: (amount) => `ਭੁਗਤਾਨ ₹${amount}`,
    statusLabel: (status) => `ਸਥਿਤੀ: ${status}`,
    rechargeShort: (amount) => `ਰੀਚਾਰਜ ₹${amount}`,
    payoutShort: (amount) => `ਭੁਗਤਾਨ ₹${amount}`,
    describeOwnWordsSubtitle: "ਆਪਣੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਦੱਸੋ",
    noneOfThesePrompt: "ਕੋਈ ਗੱਲ ਨਹੀਂ — ਕੀ ਹੋ ਰਿਹਾ ਹੈ ਆਪਣੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਦੱਸੋ।",
    commonQuestionsLabel: "ਆਮ ਸਵਾਲ",
    couldntLoadTickets: "ਤੁਹਾਡੀਆਂ ਟਿਕਟਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ — ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    noTicketsYet: "ਹਾਲੇ ਕੋਈ ਟਿਕਟ ਨਹੀਂ ਹੈ। ਚੈਟ ਵਿੱਚ ਤੁਸੀਂ ਜੋ ਵੀ ਉਠਾਓਗੇ ਉਹ ਇੱਥੇ ਦਿਖੇਗਾ।",
    attachmentErrorDefault: "ਉਹ ਫਾਈਲ ਨੱਥੀ ਨਹੀਂ ਹੋ ਸਕੀ — ਛੋਟੀ ਤਸਵੀਰ ਅਜ਼ਮਾਓ (JPEG/PNG/WEBP/HEIC, 8MB ਤੋਂ ਘੱਟ)।",
  },
  or: {
    greeting: (name) => `ନମସ୍କାର ${name}, ମୁଁ Dostt AI Assistant. ଆଜି ଆପଣଙ୍କୁ କି ସାହାଯ୍ୟ ଦରକାର?`,
    catCalls: "ସାମ୍ପ୍ରତିକ କଲ୍‌ଗୁଡ଼ିକ",
    catCallsSub: "କଲ୍ ସମ୍ବନ୍ଧୀୟ ସମସ୍ୟା",
    catTx: "ସାମ୍ପ୍ରତିକ କାରବାର",
    catTxSub: "ରିଚାର୍ଜ, ୱାଲେଟ୍ କିମ୍ବା ଉଠାଣ ସମସ୍ୟା",
    catOther: "ଅନ୍ୟ ସମସ୍ୟା",
    catOtherSub: "ଆଉ କିଛି କହିବାକୁ ଅଛି କି",
    freeTextPlaceholder: "ଆପଣଙ୍କ ବାର୍ତ୍ତା ଟାଇପ୍ କରନ୍ତୁ…",
    anythingElse: "ଆଉ କିଛି ସାହାଯ୍ୟ ଦରକାର କି?",
    yes: "ହଁ",
    no: "ନା",
    closeMsg: "ଧନ୍ୟବାଦ, ବର୍ତ୍ତମାନ ଆପଣ ଏହି ଚାଟ୍ ବନ୍ଦ କରିପାରିବେ।",
    restart: "ପୁଣି ଆରମ୍ଭ କରନ୍ତୁ",
    noneOfThese: "ଏଥିମଧ୍ୟରୁ କୌଣସିଟି ନୁହେଁ — ମୋତେ କହିବାକୁ ଦିଅନ୍ତୁ",
    connectionError: "କ୍ଷମା କରନ୍ତୁ, ପଠାଇ ପାରିଲୁ ନାହିଁ — ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
    needsGeminiKey: "ଏହି ପରିବେଶରେ ଚାଟ୍ ଏଜେଣ୍ଟ୍ ଏପର୍ଯ୍ୟନ୍ତ ସମ୍ପୂର୍ଣ୍ଣ ଭାବରେ କନଫିଗର ହୋଇନାହିଁ — ବାକି ସବୁ ସାଧାରଣ ଭାବରେ କାମ କରେ।",
    connecting: "ସଂଯୋଗ ହେଉଛି…",
    couldntStartSession: (msg) => `ସେସନ୍ ଆରମ୍ଭ ହୋଇପାରିଲା ନାହିଁ: ${msg}`,
    catOtherPrompt: "ଠିକ୍ ଅଛି — ତଳେ ଆପଣଙ୍କ ସମସ୍ୟା ନିଜ ଭାଷାରେ ଟାଇପ୍ କରନ୍ତୁ।",
    noRecentActivity: "କୌଣସି ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ ମିଳିଲା ନାହିଁ।",
    callWith: (isVideo, name) => `${name} ସହିତ ${isVideo ? "ଭିଡିଓ" : "ଅଡିଓ"} କଲ୍`,
    durationCoins: (dur, coins) => `${dur} • ${coins} କଏନ୍`,
    earningsOrPayouts: "ଏହା ଆପଣଙ୍କ ରୋଜଗାର କିମ୍ବା ପେଆଉଟ୍ ସମ୍ବନ୍ଧୀୟ କି?",
    earningsLabel: "ରୋଜଗାର",
    payoutsLabel: "ପେଆଉଟ୍",
    rechargeCard: (amount, coins) => `ରିଚାର୍ଜ ₹${amount} → ${coins} କଏନ୍`,
    payoutCard: (amount) => `ପେଆଉଟ୍ ₹${amount}`,
    statusLabel: (status) => `ସ୍ଥିତି: ${status}`,
    rechargeShort: (amount) => `ରିଚାର୍ଜ ₹${amount}`,
    payoutShort: (amount) => `ପେଆଉଟ୍ ₹${amount}`,
    describeOwnWordsSubtitle: "ନିଜ ଭାଷାରେ ବର୍ଣ୍ଣନା କରନ୍ତୁ",
    noneOfThesePrompt: "କିଛି ହରକତ ନାହିଁ — କଣ ହେଉଛି ନିଜ ଭାଷାରେ କୁହନ୍ତୁ।",
    commonQuestionsLabel: "ସାଧାରଣ ପ୍ରଶ୍ନ",
    couldntLoadTickets: "ଆପଣଙ୍କ ଟିକେଟ୍ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ — ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
    noTicketsYet: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଟିକେଟ୍ ନାହିଁ। ଚାଟ୍‌ରେ ଆପଣ ଉଠାଇଥିବା ବିଷୟ ଏଠାରେ ଦେଖାଯିବ।",
    attachmentErrorDefault: "ସେହି ଫାଇଲ୍ ସଂଲଗ୍ନ ହୋଇପାରିଲା ନାହିଁ — ଛୋଟ ଛବି ଚେଷ୍ଟା କରନ୍ତୁ (JPEG/PNG/WEBP/HEIC, 8MB ରୁ କମ୍)।",
  },
};

// FAQ_SUGGESTIONS used to be one hardcoded English array shown on every
// first empty state regardless of language — now keyed by language, same
// native-speaker-QA caveat as I18N above. app.js falls back to `en` for
// any language not listed here (kept in sync with I18N's key set).
const FAQ_SUGGESTIONS_I18N = {
  en: [
    "How do I change my app language?",
    "How do I become a Listener?",
    "How do I delete my account?",
    "Why is my account blocked?",
  ],
  hi: [
    "मैं अपनी ऐप की भाषा कैसे बदलूं?",
    "मैं Listener कैसे बनूं?",
    "मैं अपना अकाउंट कैसे डिलीट करूं?",
    "मेरा अकाउंट ब्लॉक क्यों है?",
  ],
  kn: [
    "ನನ್ನ ಆ್ಯಪ್ ಭಾಷೆಯನ್ನು ಹೇಗೆ ಬದಲಾಯಿಸಲಿ?",
    "ನಾನು Listener ಆಗುವುದು ಹೇಗೆ?",
    "ನನ್ನ ಖಾತೆಯನ್ನು ಹೇಗೆ ಡಿಲೀಟ್ ಮಾಡಲಿ?",
    "ನನ್ನ ಖಾತೆ ಏಕೆ ಬ್ಲಾಕ್ ಆಗಿದೆ?",
  ],
  ta: [
    "எனது ஆப் மொழியை எப்படி மாற்றுவது?",
    "நான் Listener ஆவது எப்படி?",
    "எனது கணக்கை எப்படி நீக்குவது?",
    "எனது கணக்கு ஏன் தடுக்கப்பட்டுள்ளது?",
  ],
  te: [
    "నా యాప్ భాషను ఎలా మార్చాలి?",
    "నేను Listener గా ఎలా మారాలి?",
    "నా ఖాతాను ఎలా తొలగించాలి?",
    "నా ఖాతా ఎందుకు బ్లాక్ అయింది?",
  ],
  ml: [
    "എന്റെ ആപ്പ് ഭാഷ എങ്ങനെ മാറ്റാം?",
    "ഞാൻ എങ്ങനെ Listener ആകാം?",
    "എന്റെ അക്കൗണ്ട് എങ്ങനെ ഡിലീറ്റ് ചെയ്യാം?",
    "എന്റെ അക്കൗണ്ട് എന്തുകൊണ്ട് ബ്ലോക്ക് ആയി?",
  ],
  mr: [
    "माझ्या अ‍ॅपची भाषा कशी बदलू?",
    "मी Listener कसा होऊ?",
    "माझे अकाउंट कसे डिलीट करू?",
    "माझे अकाउंट का ब्लॉक झाले आहे?",
  ],
  bn: [
    "আমার অ্যাপের ভাষা কীভাবে পরিবর্তন করব?",
    "আমি কীভাবে Listener হব?",
    "আমার অ্যাকাউন্ট কীভাবে ডিলিট করব?",
    "আমার অ্যাকাউন্ট কেন ব্লক হয়েছে?",
  ],
  gu: [
    "મારી એપની ભાષા કેવી રીતે બદલું?",
    "હું Listener કેવી રીતે બનું?",
    "મારું એકાઉન્ટ કેવી રીતે ડિલીટ કરું?",
    "મારું એકાઉન્ટ કેમ બ્લોક થયું છે?",
  ],
  pa: [
    "ਮੈਂ ਆਪਣੀ ਐਪ ਦੀ ਭਾਸ਼ਾ ਕਿਵੇਂ ਬਦਲਾਂ?",
    "ਮੈਂ Listener ਕਿਵੇਂ ਬਣਾਂ?",
    "ਮੈਂ ਆਪਣਾ ਅਕਾਊਂਟ ਕਿਵੇਂ ਡਿਲੀਟ ਕਰਾਂ?",
    "ਮੇਰਾ ਅਕਾਊਂਟ ਕਿਉਂ ਬਲਾਕ ਹੈ?",
  ],
  or: [
    "ମୁଁ ମୋ ଆପ୍ ଭାଷା କିପରି ବଦଳାଇବି?",
    "ମୁଁ Listener କିପରି ହେବି?",
    "ମୁଁ ମୋ ଆକାଉଣ୍ଟ କିପରି ଡିଲିଟ୍ କରିବି?",
    "ମୋ ଆକାଉଣ୍ଟ କାହିଁକି ବ୍ଲକ୍ ହୋଇଛି?",
  ],
};

function t(lang, key, ...args) {
  const dict = I18N[lang] || I18N.en;
  const val = dict[key] ?? I18N.en[key];
  return typeof val === "function" ? val(...args) : val;
}
